[world]
kind = "WorldContract"
class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
original_class_hash = "0x458d0ce5b14a4844092bdb62050f462d53362304a13febbac6d973691d61be2"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x64ba78fe3ab8aedf19206180187d77a8b20b2a1f94877e18b86cb92dca82334"
transaction_hash = "0x7f60381b90f4a4ea937b89f903df43b1836e7c39f50b544bd37046c6e8ae8ca"
block_number = 3
seed = "dojo_starter_rpg"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://0.0.0.0:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x1d93c48dc21d50f6d51e1d73e91a130fe0b5669d5e3f643acd8cc4ded547362"
class_hash = "0x13c14b0de3cfeb7664b7ef2f52faa40c59298fe0fa98303deb8294826159307"
original_class_hash = "0x13c14b0de3cfeb7664b7ef2f52faa40c59298fe0fa98303deb8294826159307"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/tisland-gameroom-629cbb8e.json"
reads = []
writes = [
    "tisland-Player",
    "tisland-GameRoom",
    "tisland-Round",
    "tisland-IslandCoords",
    "tisland-Loot",
    "tisland-ArrayTester",
    "tisland-LootObject",
    "tisland-LootTracker",
    "tisland-Guesses",
    "tisland-Gold",
]
init_calldata = []
tag = "tisland-gameroom"
manifest_name = "tisland-gameroom-629cbb8e"

[[contracts]]
kind = "DojoContract"
address = "0x5e3bdf1ab1fb27d359f3de189277420b5154325da6e94312714c5087ba5fc28"
class_hash = "0x45198908e9cbb52146adb7d412208f26cd50fa4fe17f96bf033a26ca79b0953"
original_class_hash = "0x45198908e9cbb52146adb7d412208f26cd50fa4fe17f96bf033a26ca79b0953"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/tisland-lobby-2ffc4f17.json"
reads = []
writes = [
    "tisland-Player",
    "tisland-GameRoom",
    "tisland-Round",
    "tisland-IslandCoords",
    "tisland-Loot",
    "tisland-ArrayTester",
    "tisland-LootObject",
    "tisland-LootTracker",
    "tisland-Guesses",
]
init_calldata = []
tag = "tisland-lobby"
manifest_name = "tisland-lobby-2ffc4f17"

[[models]]
kind = "DojoModel"
class_hash = "0x75444238acf97681924d47c9628b9498005a7b3483b05213a849439ed83ec6"
original_class_hash = "0x75444238acf97681924d47c9628b9498005a7b3483b05213a849439ed83ec6"
abi = "manifests/dev/deployment/abis/models/tisland-ArrayTester-7924f4da.json"
tag = "tisland-ArrayTester"
manifest_name = "tisland-ArrayTester-7924f4da"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "mapunits"
type = "Array<u8>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4eb2863266027effc525a3303e28c8175ca4acd3193684f1b0efb93c5304ad2"
original_class_hash = "0x4eb2863266027effc525a3303e28c8175ca4acd3193684f1b0efb93c5304ad2"
abi = "manifests/dev/deployment/abis/models/tisland-GameRoom-1b416b58.json"
tag = "tisland-GameRoom"
manifest_name = "tisland-GameRoom-1b416b58"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player1"
type = "ContractAddress"
key = false

[[models.members]]
name = "player2"
type = "ContractAddress"
key = false

[[models.members]]
name = "invited_player"
type = "ContractAddress"
key = false

[[models.members]]
name = "state"
type = "u8"
key = false

[[models.members]]
name = "round_num"
type = "u8"
key = false

[[models.members]]
name = "phase"
type = "u8"
key = false

[[models.members]]
name = "winner"
type = "ContractAddress"
key = false

[[models.members]]
name = "timestamp_start"
type = "u64"
key = false

[[models.members]]
name = "expiry_time"
type = "u64"
key = false

[[models.members]]
name = "timestamp_end"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x786d88461b5acfc72fb5c2e047610cc41f74e0d7ed60e73405b7492adc3d1cc"
original_class_hash = "0x786d88461b5acfc72fb5c2e047610cc41f74e0d7ed60e73405b7492adc3d1cc"
abi = "manifests/dev/deployment/abis/models/tisland-Gold-59b32d3a.json"
tag = "tisland-Gold"
manifest_name = "tisland-Gold-59b32d3a"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = false

[[models.members]]
name = "balance"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4d35a1c0467e75e761d7fc827a5e99832eec483936462ebf11a3a3e987fdc63"
original_class_hash = "0x4d35a1c0467e75e761d7fc827a5e99832eec483936462ebf11a3a3e987fdc63"
abi = "manifests/dev/deployment/abis/models/tisland-Guesses-78c25d7e.json"
tag = "tisland-Guesses"
manifest_name = "tisland-Guesses-78c25d7e"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "index"
type = "u8"
key = false

[[models.members]]
name = "round_number"
type = "u8"
key = false

[[models.members]]
name = "correct"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x21ca4e159fb502c0d978a2f8a0407739bbd478043b32f998d4179a0564d37bd"
original_class_hash = "0x21ca4e159fb502c0d978a2f8a0407739bbd478043b32f998d4179a0564d37bd"
abi = "manifests/dev/deployment/abis/models/tisland-IslandCoords-58e488a1.json"
tag = "tisland-IslandCoords"
manifest_name = "tisland-IslandCoords-58e488a1"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "x"
type = "u8"
key = true

[[models.members]]
name = "y"
type = "u8"
key = true

[[models.members]]
name = "index"
type = "u8"
key = false

[[models.members]]
name = "terrain"
type = "u8"
key = false

[[models.members]]
name = "loot_id"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x47de44001a9d5de5a10a321980b719c33ce5a005ad84534031e41c60d0df378"
original_class_hash = "0x47de44001a9d5de5a10a321980b719c33ce5a005ad84534031e41c60d0df378"
abi = "manifests/dev/deployment/abis/models/tisland-Loot-29fe4a7e.json"
tag = "tisland-Loot"
manifest_name = "tisland-Loot-29fe4a7e"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "four_one"
type = "u8"
key = false

[[models.members]]
name = "four_one_hidden"
type = "u8"
key = false

[[models.members]]
name = "four_one_indices"
type = "Array<u8>"
key = false

[[models.members]]
name = "three_one"
type = "u8"
key = false

[[models.members]]
name = "three_one_hidden"
type = "u8"
key = false

[[models.members]]
name = "three_one_indices"
type = "Array<u8>"
key = false

[[models.members]]
name = "two_one"
type = "u8"
key = false

[[models.members]]
name = "two_one_hidden"
type = "u8"
key = false

[[models.members]]
name = "two_one_indices"
type = "Array<u8>"
key = false

[[models.members]]
name = "one_one"
type = "u8"
key = false

[[models.members]]
name = "one_one_hidden"
type = "u8"
key = false

[[models.members]]
name = "one_one_indices"
type = "Array<u8>"
key = false

[[models.members]]
name = "shovels"
type = "u8"
key = false

[[models.members]]
name = "traps"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2ed9acf48c1909695d6df9c8c204fd4bef1d2dff7bf69a07ecae951e754875f"
original_class_hash = "0x2ed9acf48c1909695d6df9c8c204fd4bef1d2dff7bf69a07ecae951e754875f"
abi = "manifests/dev/deployment/abis/models/tisland-LootObject-74a9c867.json"
tag = "tisland-LootObject"
manifest_name = "tisland-LootObject-74a9c867"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "loot_id"
type = "u8"
key = true

[[models.members]]
name = "loot_length"
type = "u8"
key = false

[[models.members]]
name = "hidden_indices"
type = "Array<u8>"
key = false

[[models.members]]
name = "revealed_indices"
type = "Array<u8>"
key = false

[[models.members]]
name = "hidden"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6979e870fa8ea9275c7286c88fd9d1d16819a9a3d11478b9959eac6b8bdaa2b"
original_class_hash = "0x6979e870fa8ea9275c7286c88fd9d1d16819a9a3d11478b9959eac6b8bdaa2b"
abi = "manifests/dev/deployment/abis/models/tisland-LootTracker-548425eb.json"
tag = "tisland-LootTracker"
manifest_name = "tisland-LootTracker-548425eb"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "loot_ids"
type = "Array<u8>"
key = false

[[models.members]]
name = "loot_count"
type = "LOcounter"
key = false

[[models.members]]
name = "loot_hidden_count"
type = "LOcounter"
key = false

[[models.members]]
name = "shovels"
type = "u8"
key = false

[[models.members]]
name = "traps"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x723965f7d48a22aaad5e212e08f1e80b6f7f5484382ffa87a9a0d6f9ea33493"
original_class_hash = "0x723965f7d48a22aaad5e212e08f1e80b6f7f5484382ffa87a9a0d6f9ea33493"
abi = "manifests/dev/deployment/abis/models/tisland-Player-3979016e.json"
tag = "tisland-Player"
manifest_name = "tisland-Player-3979016e"

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "pfp_num"
type = "u8"
key = false

[[models.members]]
name = "timestamp"
type = "u64"
key = false

[[models.members]]
name = "score"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6630349064d645446daf8ca75db297e973ae579e9322eb907352e5a14483825"
original_class_hash = "0x6630349064d645446daf8ca75db297e973ae579e9322eb907352e5a14483825"
abi = "manifests/dev/deployment/abis/models/tisland-Round-551e834e.json"
tag = "tisland-Round"
manifest_name = "tisland-Round-551e834e"

[[models.members]]
name = "game_id"
type = "u128"
key = true

[[models.members]]
name = "round_number"
type = "u8"
key = true

[[models.members]]
name = "player1_tries"
type = "u8"
key = false

[[models.members]]
name = "player2_tries"
type = "u8"
key = false
